name: trigger-checks
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Push changes
        env:
          BRANCH_REF: ${{ github.ref_name }}
        run: |-
          git commit --allow-empty -m "chore: trigger checks"
          git push origin HEAD:$BRANCH_REF
